"""
Label dataset orchestration for the River Morphology Segmentation System
(Module 9).

LabelManager organizes, validates, and versions segmentation label masks
against patches generated by Module 8, preserving full temporal context
required for time-varying river morphology (sandbars that vegetate,
channels that migrate, seasonal water extent changes).

Architecture: LabelSource -> LabelValidator -> TemporalMetadataBuilder ->
LabelStatisticsCalculator -> LabelManifestManager -> LabelManager
(orchestrator).

LabelManager depends only on the LabelSource ABSTRACTION, not on any
specific discovery mechanism. Swapping FilesystemLabelSource for a future
SAM-based or GIS-based source requires zero changes to this class.

No GeoTIFF writing logic is reimplemented; label mask files are copied
(not rewritten) into the organized output layout.

Output layout:
    {output_dir}/
        label_manifest.csv
        label_manifest.json
        scenes/
            {scene_id}/
                labels/
                    {patch_id}_mask.tif
                    ...

Input contract:  PatchDatasetResult (Module 8) + SceneMetadata (Module 7,
                 reused) + a LabelSource for mask discovery.
Output contract: LabelDatasetResult (immutable)
"""

from __future__ import annotations

import logging
import shutil
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

from src.core.config import Config
from src.core.exceptions import InvalidValueError
from src.labels.manifest import (
    LabelManifest,
    LabelManifestEntry,
    LabelManifestManager,
)
from src.labels.schema import ClassSchema
from src.labels.source import FilesystemLabelSource, LabelSource
from src.labels.statistics import LabelStatistics, LabelStatisticsCalculator
from src.labels.temporal import (
    HydrologicalYearResolver,
    SeasonResolver,
    TemporalMetadataBuilder,
    validate_temporal_consistency,
)
from src.labels.validator import LabelValidator

if TYPE_CHECKING:
    from src.export.metadata import SceneMetadata
    from src.patches.generator import PatchDatasetResult

__all__ = ["LabelDatasetResult", "LabelManager"]

_LOGGER: logging.Logger = logging.getLogger(__name__)

_SCENES_SUBDIR: str = "scenes"
_LABELS_SUBDIR: str = "labels"


# ==============================================================================
# LabelDatasetResult
# ==============================================================================

@dataclass(frozen=True)
class LabelDatasetResult:
    """
    Immutable output of LabelManager.generate().

    Attributes:
        scene_id:            Source scene identifier.
        output_dir:            Root directory for the label dataset.
        scene_labels_dir:        Directory containing this scene's organized
                                label mask files.
        manifest:                Frozen LabelManifest snapshot after this run.
        statistics:               Aggregated LabelStatistics for this run.
        class_schema:             ClassSchema used for validation.
        source_type:               Identifier of the LabelSource implementation
                                used to discover masks for this run.
        labels_processed:          Total label candidates processed (excludes
                                duplicates skipped).
        labels_valid:              Count of labels that passed validation.
        labels_rejected:            Count of labels that failed validation.
        labels_missing:              Count of patches with no corresponding mask.
        labels_duplicate:             Count of duplicate patch_id labels skipped.
        operations_log:               Ordered tuple of operation descriptions.
    """

    scene_id:            str
    output_dir:            Path
    scene_labels_dir:        Path
    manifest:                 LabelManifest
    statistics:                LabelStatistics
    class_schema:               ClassSchema
    source_type:                 str
    labels_processed:            int
    labels_valid:                 int
    labels_rejected:               int
    labels_missing:                 int
    labels_duplicate:                int
    operations_log:                   tuple[str, ...]

    def summary_lines(self) -> list[str]:
        """Return ASCII-formatted summary lines."""
        return [
            f"  scene_id:          {self.scene_id}",
            f"  source_type:        {self.source_type}",
            f"  labels processed:    {self.labels_processed}",
            f"  labels valid:         {self.labels_valid}",
            f"  labels rejected:       {self.labels_rejected}",
            f"  labels missing:         {self.labels_missing}",
            f"  labels duplicate:        {self.labels_duplicate}",
        ]


# ==============================================================================
# LabelManager
# ==============================================================================

class LabelManager:
    """
    Orchestrates label discovery, validation, temporal annotation, and
    organization.

    All thresholds and defaults are sourced from config.labels and
    config.temporal. Never hardcodes class IDs, season boundaries,
    hydrological year boundaries, or validation thresholds.

    Args:
        config: Fully initialized Config object.
    """

    def __init__(self, config: Config) -> None:
        self._config = config
        self._logger: logging.Logger = logging.getLogger(__name__)

        self._class_schema = ClassSchema.from_config(config)
        self._season_resolver = SeasonResolver.from_config(config)
        self._hydro_year_resolver = HydrologicalYearResolver.from_config(config)
        self._temporal_builder = TemporalMetadataBuilder(
            self._season_resolver, self._hydro_year_resolver, config
        )

        labels_cfg = getattr(config, "labels", None)
        self._nodata_value = int(getattr(labels_cfg, "nodata_value", 255))
        self._max_nodata_ratio = float(getattr(labels_cfg, "max_nodata_ratio", 0.5))
        self._min_distinct_classes = int(getattr(labels_cfg, "min_distinct_classes", 1))
        self._reject_single_class_masks = bool(
            getattr(labels_cfg, "reject_single_class_masks", False)
        )
        self._manifest_formats = [
            str(f).lower()
            for f in getattr(labels_cfg, "output_formats", ["csv", "json"])
        ]

        self._validator = LabelValidator(
            class_schema=self._class_schema,
            nodata_value=self._nodata_value,
            max_nodata_ratio=self._max_nodata_ratio,
            min_distinct_classes=self._min_distinct_classes,
            reject_single_class_masks=self._reject_single_class_masks,
        )

        self._logger.debug(
            "LabelManager initialized. classes=%d, nodata=%d, "
            "max_nodata_ratio=%.2f, hydro_year_start=%d",
            self._class_schema.num_classes, self._nodata_value,
            self._max_nodata_ratio, self._hydro_year_resolver.start_month,
        )

    # ------------------------------------------------------------------
    # Public
    # ------------------------------------------------------------------

    def generate(
        self,
        patch_dataset_result: PatchDatasetResult,
        scene_metadata:        SceneMetadata,
        output_dir:              Path,
        aoi_id:                  str,
        label_source:             LabelSource | None = None,
        labels_source_dir:        Path | None = None,
        river_name:              str | None = None,
        reach_id:                 str | None = None,
        basin_id:                 str | None = None,
        label_version:           str | None = None,
        annotator:               str | None = None,
        confidence:              float | None = None,
        confidence_source:        str | None = None,
        append_to_manifest:      bool = True,
    ) -> LabelDatasetResult:
        """
        Discover, validate, annotate, and organize labels for one scene's patches.

        Mask discovery is delegated entirely to a LabelSource. Either
        provide a fully constructed label_source (any LabelSource
        implementation), or provide labels_source_dir for the convenience
        of defaulting to FilesystemLabelSource.from_config().

        Sequence:
            1. Resolve the LabelSource.
            2. Create output directory tree.
            3. Load existing manifest (if append_to_manifest) to detect
               cross-run duplicates.
            4. Call label_source.discover() for all patch IDs in one pass.
            5. For each patch in patch_dataset_result.manifest.entries:
                 a. Skip if patch_id is a duplicate (already recorded).
                 b. Validate the discovered mask against the patch (CRS,
                    transform, dimensions, class content).
                 c. Build TemporalMetadata and check temporal consistency.
                 d. Copy the mask into the organized output layout (if found).
                 e. Accumulate statistics.
                 f. Record a LabelManifestEntry.
            6. Persist label_manifest.csv / label_manifest.json.
            7. Return LabelDatasetResult.

        Args:
            patch_dataset_result:   PatchDatasetResult from Module 8.
            scene_metadata:           SceneMetadata, reused from Module 7's
                                   DatasetExportResult.scene_metadata.
            output_dir:                 Root directory for the organized
                                   label dataset. Created if absent.
            aoi_id:                     Identifier for the configured AOI.
            label_source:               Fully constructed LabelSource. Takes
                                   precedence over labels_source_dir.
            labels_source_dir:           Directory of pre-existing label mask
                                   GeoTIFFs. Used to build a
                                   FilesystemLabelSource when label_source
                                   is not provided.
            river_name:                 Optional river name for all labels
                                   in this run.
            reach_id:                   Optional river reach identifier.
            basin_id:                   Optional drainage basin identifier.
            label_version:              Override label version for this run.
            annotator:                  Override annotator for this run.
            confidence:                 Override confidence for this run.
            confidence_source:           Override confidence source for this run.
            append_to_manifest:          Load and extend an existing label
                                   manifest when True; start fresh when False.

        Returns:
            Frozen LabelDatasetResult.

        Raises:
            InvalidValueError: patch_dataset_result has no patch entries,
                               or neither label_source nor labels_source_dir
                               is provided.
        """
        scene_id = patch_dataset_result.scene_id
        patch_entries = patch_dataset_result.manifest.entries
        if not patch_entries:
            raise InvalidValueError(
                field="patch_dataset_result.manifest.entries",
                value=0,
                reason="must contain at least one patch entry to generate labels",
            )

        resolved_source = self._resolve_label_source(label_source, labels_source_dir)

        output_dir = Path(output_dir).resolve()
        scene_labels_dir = output_dir / _SCENES_SUBDIR / scene_id / _LABELS_SUBDIR
        scene_labels_dir.mkdir(parents=True, exist_ok=True)

        operations: list[str] = []
        self._logger.info(
            "Generating labels. scene_id=%s, patches=%d, source=%s",
            scene_id, len(patch_entries), resolved_source.source_type,
        )

        manifest_manager = LabelManifestManager()
        if append_to_manifest:
            manifest_manager.load_existing(output_dir)
        existing_ids = {e.patch_id for e in manifest_manager.entries}

        stats_calc = LabelStatisticsCalculator.from_config(self._class_schema, self._config)

        patch_ids = tuple(e.patch_id for e in patch_entries)
        discovery_records = {
            r.patch_id: r for r in resolved_source.discover(patch_ids)
        }
        operations.append(
            f"discovery: {sum(1 for r in discovery_records.values() if r.found)}"
            f"/{len(patch_ids)} mask(s) found via '{resolved_source.source_type}'"
        )

        valid_count = 0
        rejected_count = 0
        missing_count = 0
        duplicate_count = 0
        seen_this_run: set[str] = set()

        for patch_entry in patch_entries:
            patch_id = patch_entry.patch_id

            if patch_id in existing_ids or patch_id in seen_this_run:
                duplicate_count += 1
                self._logger.warning("Skipping duplicate patch_id: %s", patch_id)
                continue
            seen_this_run.add(patch_id)

            source_record = discovery_records.get(patch_id)
            source_mask_path = source_record.mask_path if source_record else None

            validation = self._validator.validate(
                Path(patch_entry.patch_path), source_mask_path
            )
            if not validation.mask_exists:
                missing_count += 1

            temporal = self._temporal_builder.build(
                scene_id=scene_id,
                patch_id=patch_id,
                scene_start_date=scene_metadata.start_date,
                scene_end_date=scene_metadata.end_date,
                sensors=scene_metadata.sensors,
                aoi_id=aoi_id,
                river_name=river_name,
                reach_id=reach_id,
                basin_id=basin_id,
                label_version=label_version,
                annotator=annotator,
                confidence=confidence,
                confidence_source=confidence_source,
                processing_history=("discovered", "validated", "organized"),
            )
            temporal_ok, temporal_issues = validate_temporal_consistency(
                temporal, self._season_resolver, self._hydro_year_resolver,
            )

            combined_issues = validation.issues + temporal_issues
            is_valid = validation.is_valid and temporal_ok

            dest_mask_path = source_mask_path
            mask_array: Any | None = None
            if validation.mask_exists and source_mask_path is not None:
                dest_mask_path = scene_labels_dir / source_mask_path.name
                self._copy_mask(source_mask_path, dest_mask_path)
                mask_array = self._read_mask_array(source_mask_path)

            stats_calc.accumulate(
                mask_data=mask_array,
                validation_result=validation,
                temporal_metadata=temporal,
            )

            if is_valid:
                valid_count += 1
            else:
                rejected_count += 1

            entry = LabelManifestEntry(
                patch_id=patch_id,
                scene_id=scene_id,
                patch_path=str(patch_entry.patch_path),
                mask_path=str(dest_mask_path) if dest_mask_path else "",
                crs=patch_entry.crs,
                width=patch_entry.width,
                height=patch_entry.height,
                is_valid=is_valid,
                validation_issues="; ".join(combined_issues),
                num_classes_present=validation.num_classes_present,
                valid_pixel_ratio=validation.valid_pixel_ratio,
                source_type=resolved_source.source_type,
                acquisition_date=temporal.acquisition_date,
                year=temporal.year,
                month=temporal.month,
                season=temporal.season,
                hydrological_year=temporal.hydrological_year,
                sensor=temporal.sensor,
                river_name=temporal.river_name or "",
                reach_id=temporal.reach_id or "",
                basin_id=temporal.basin_id or "",
                aoi_id=temporal.aoi_id,
                label_version=temporal.label_version,
                annotator=temporal.annotator,
                confidence=temporal.confidence,
                confidence_source=temporal.confidence_source,
                processing_history=",".join(temporal.processing_history),
                created_at=datetime.now(timezone.utc).isoformat(),
            )
            manifest_manager.add_entry(entry)

        operations.append(
            f"processed: {len(seen_this_run)}, duplicates_skipped: {duplicate_count}"
        )
        operations.append(
            f"valid: {valid_count}, rejected: {rejected_count}, missing: {missing_count}"
        )

        manifest = manifest_manager.save(output_dir, formats=self._manifest_formats)
        operations.append(f"write_manifest: {manifest.entry_count} total entries")

        statistics = stats_calc.compute()

        result = LabelDatasetResult(
            scene_id=scene_id,
            output_dir=output_dir,
            scene_labels_dir=scene_labels_dir,
            manifest=manifest,
            statistics=statistics,
            class_schema=self._class_schema,
            source_type=resolved_source.source_type,
            labels_processed=len(seen_this_run),
            labels_valid=valid_count,
            labels_rejected=rejected_count,
            labels_missing=missing_count,
            labels_duplicate=duplicate_count,
            operations_log=tuple(operations),
        )

        for line in result.summary_lines():
            self._logger.info(line)

        return result

    # ------------------------------------------------------------------
    # Private
    # ------------------------------------------------------------------

    def _resolve_label_source(
        self,
        label_source:        LabelSource | None,
        labels_source_dir:     Path | None,
    ) -> LabelSource:
        """
        Determine which LabelSource to use for this run.

        Priority: explicit label_source argument, then labels_source_dir
        (wrapped in a config-driven FilesystemLabelSource).

        Raises:
            InvalidValueError: neither argument is provided.
        """
        if label_source is not None:
            return label_source
        if labels_source_dir is not None:
            return FilesystemLabelSource.from_config(self._config, labels_source_dir)
        raise InvalidValueError(
            field="label_source / labels_source_dir",
            value=None,
            reason=(
                "either label_source (a LabelSource instance) or "
                "labels_source_dir (a Path, wrapped in FilesystemLabelSource) "
                "must be provided"
            ),
        )

    @staticmethod
    def _copy_mask(source: Path, dest: Path) -> None:
        """Copy a mask file into the organized output layout, preserving metadata."""
        if source.resolve() == dest.resolve():
            return
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, dest)

    @staticmethod
    def _read_mask_array(mask_path: Path) -> Any | None:
        """Read band 1 of a mask GeoTIFF. Returns None on any failure."""
        try:
            import rasterio
            with rasterio.open(mask_path) as ds:
                return ds.read(1)
        except Exception:
            return None