"""
Label source abstraction for the label management pipeline (Module 9).

LabelSource decouples LabelManager from any specific mechanism by which
label masks are produced or stored. Today, FilesystemLabelSource discovers
masks already present on disk (manually annotated, GIS-derived, or
auto-generated by an external tool). Future implementations -- e.g. a
SAM-based auto-annotation source, a remote label store, or a GIS feature
service -- can be added by implementing the LabelSource interface without
any change to LabelManager.

LabelSource implementations are responsible ONLY for locating a mask
given a patch_id. They perform no validation (LabelValidator's job) and
no file copying or organization (LabelManager's job).
"""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from src.core.config import Config

__all__ = ["LabelSourceRecord", "LabelSource", "FilesystemLabelSource"]

_LOGGER: logging.Logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class LabelSourceRecord:
    """
    Immutable result of looking up one patch's label mask via a LabelSource.

    Attributes:
        patch_id:     The patch identifier this record applies to.
        mask_path:     Absolute path to the discovered mask file, or None
                       if no mask was found.
        found:          True if mask_path is non-None and was located by
                       the source.
        source_type:    Identifier for the LabelSource implementation that
                       produced this record, e.g. "filesystem", "sam".
    """

    patch_id:    str
    mask_path:    Path | None
    found:         bool
    source_type:    str


class LabelSource(ABC):
    """
    Abstract interface for discovering label masks corresponding to patches.

    Implementations must be stateless with respect to validation outcomes:
    discover() only reports whether and where a mask exists, never whether
    it is valid.
    """

    @property
    @abstractmethod
    def source_type(self) -> str:
        """Short ASCII identifier for this source implementation."""

    @abstractmethod
    def discover(self, patch_ids: tuple[str, ...]) -> tuple[LabelSourceRecord, ...]:
        """
        Locate label masks for the given patch IDs.

        Args:
            patch_ids: Patch identifiers to look up, in the order they
                       should be processed.

        Returns:
            One LabelSourceRecord per patch_id, in the same order as
            patch_ids. found=False (mask_path=None) for any patch with
            no discoverable mask.
        """


class FilesystemLabelSource(LabelSource):
    """
    Discovers label masks from a directory using a configurable filename pattern.

    Args:
        labels_dir:         Directory containing label mask GeoTIFFs.
        filename_pattern:    Pattern containing a "{patch_id}" placeholder,
                            e.g. "{patch_id}_mask.tif". Sourced from
                            config.labels.mask_filename_pattern.

    Raises:
        InvalidValueError: filename_pattern does not contain "{patch_id}".
    """

    _SOURCE_TYPE: str = "filesystem"

    def __init__(self, labels_dir: Path, filename_pattern: str) -> None:
        from src.core.exceptions import InvalidValueError

        if "{patch_id}" not in filename_pattern:
            raise InvalidValueError(
                field="labels.mask_filename_pattern",
                value=filename_pattern,
                reason="must contain the '{patch_id}' placeholder",
            )
        self._labels_dir = Path(labels_dir).resolve()
        self._filename_pattern = filename_pattern
        self._logger: logging.Logger = logging.getLogger(__name__)

    @classmethod
    def from_config(cls, config: Config, labels_dir: Path) -> FilesystemLabelSource:
        """
        Build a FilesystemLabelSource using config.labels.mask_filename_pattern.

        Args:
            config:      Fully initialized Config object.
            labels_dir:   Directory containing label mask GeoTIFFs.

        Returns:
            FilesystemLabelSource configured with the project's naming convention.
        """
        labels_cfg = getattr(config, "labels", None)
        pattern = str(
            getattr(labels_cfg, "mask_filename_pattern", "{patch_id}_mask.tif")
        )
        return cls(labels_dir, pattern)

    @property
    def source_type(self) -> str:
        return self._SOURCE_TYPE

    @property
    def labels_dir(self) -> Path:
        """The directory this source searches for mask files."""
        return self._labels_dir

    def discover(self, patch_ids: tuple[str, ...]) -> tuple[LabelSourceRecord, ...]:
        records: list[LabelSourceRecord] = []
        for patch_id in patch_ids:
            filename = self._filename_pattern.format(patch_id=patch_id)
            candidate = self._labels_dir / filename
            found = candidate.exists()
            records.append(LabelSourceRecord(
                patch_id=patch_id,
                mask_path=candidate if found else None,
                found=found,
                source_type=self._SOURCE_TYPE,
            ))

        found_count = sum(1 for r in records if r.found)
        self._logger.debug(
            "FilesystemLabelSource discovered %d/%d mask(s) in %s.",
            found_count, len(patch_ids), self._labels_dir,
        )
        return tuple(records)